"""Where every table lives, in one place.

The repository keeps three kinds of table (docs/data-layout.ja.md):

    catalog/   目録  the names everything else keys on (families, series, products …)
    evidence/  証拠  what the documents say, spelled as they spell it, with provenance
    index/     索引  lookup tables derived from evidence -- vocabulary-normalised,
                     one combined file per table

Tools ask this module for a path instead of spelling directories themselves, so
moving a table means editing one dictionary. ``table(name)`` covers catalog and
evidence (their names are unique across the two); ``index(name)`` covers the
index, whose ``registers`` / ``timers`` share a file name with evidence tables
on purpose (same subject, different layer).

    uv run python3 -c "import tools.paths as p; print(p.table('pins'))"
"""

from __future__ import annotations

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "catalog"
EVIDENCE = REPO / "evidence"
INDEX = REPO / "index"
CURATED = REPO / "curated"
CACHE = REPO / ".cache"
# Per-SKU extraction with its judgement trail; regenerated by build_all.py and
# not committed (the evidence tables are the reviewed extraction output).
CANDIDATES = CACHE / "candidates"
MIRRORS = Path("/home/mt/dev_wch")

CATALOG_TABLES = ("families", "series", "products", "packages", "cores",
                  "documents", "sources", "toolchains")

EVIDENCE_TABLES = (
    "pins", "pin_functions", "pin_alternate", "product_attributes",
    "features", "errata", "memory_configs", "adc_internal", "flash_geometry",
    "flash_program_method",
    "eval_boards", "evt_examples", "link_firmware", "operating_conditions",
    "absolute_maximum_ratings",
    "remap_fields", "remap_routes", "timers",
    "register_blocks", "registers", "register_fields", "dma_requests",
    "opa_cmp_registers", "clock_enables", "usbpd_plumbing",
    "interrupts", "memory_map", "systick", "clock_configs", "clock_prescalers",
    "clock_sources", "clock_symbols", "clock_init", "evt_variants", "debug_data",
    "debug_wiring", "option_bytes", "option_byte_fields",
    "device_id_addresses", "device_ids", "pin_conditions", "figures",
)

# Index tables: one combined file each (all parts / all families). People filter
# them in the viewer (pins.html); CSV is for programs, so there are no per-part
# copies to keep in step.
INDEX_TABLES = ("parts", "pinout", "routes", "registers", "register_map", "dma",
                "timers", "features", "capabilities", "conflicts", "register_layouts",
                "debug_interfaces")

# index/ is the whole public surface (docs/public-surface.ja.md): consumers read
# nothing outside it. Catalog and evidence tables it publishes are copied in by
# build_index.py, row for row, minus the columns named here (internal bookkeeping
# a consumer has no use for). The copy keeps the source's name.
PUBLISHED: dict[str, tuple[str, ...]] = {
    # catalog keys
    "families": (), "series": (), "cores": (), "packages": (),
    "products": ("packing", "packing_confidence", "packing_basis"),
    # evidence copied from EVT headers (the former "stable" set)
    "interrupts": (), "memory_map": (), "systick": (), "evt_variants": (),
    "clock_configs": ("evt_copies",), "clock_prescalers": (), "clock_sources": (),
    "clock_symbols": (), "clock_init": (), "clock_enables": (), "pin_alternate": (),
    "flash_geometry": (), "flash_program_method": (), "adc_internal": (), "debug_data": (),
    # evidence published on request (R-33, R-34)
    "device_ids": (), "option_bytes": (), "option_byte_fields": (), "register_blocks": (),
    "errata": (), "operating_conditions": ("datasheet",),
}
assert not set(PUBLISHED) & set(INDEX_TABLES)


def where(name: str) -> Path:
    """Directory of a catalog or evidence table."""
    if name in CATALOG_TABLES:
        return CATALOG
    if name in EVIDENCE_TABLES:
        return EVIDENCE
    raise KeyError(f"unknown table {name!r} (index tables: paths.index())")


def table(name: str, out: Path | None = None) -> Path:
    """Path of a catalog/evidence table. ``out`` overrides the directory (tests)."""
    return (out if out is not None else where(name)) / f"{name}.csv"


def index(name: str, out: Path | None = None) -> Path:
    if name not in INDEX_TABLES and name not in PUBLISHED:
        raise KeyError(f"unknown index table {name!r}")
    return (out if out is not None else INDEX) / f"{name}.csv"


def load(name: str) -> list[dict]:
    with table(name).open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def load_index(name: str) -> list[dict]:
    with index(name).open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write(path: Path, rows: list[dict], columns: list[str]) -> None:
    """Write rows with the ``#`` separator column filled in every row."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as out:
        w = csv.DictWriter(out, fieldnames=columns)
        w.writeheader()
        w.writerows({**{c: r.get(c, "") for c in columns}, "#": "#"} for r in rows)
